name: Manual Buildozer Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Buildozer and dependencies
        run: |
          sudo apt-get update
          # قائمة متطلبات محدثة ومتوافقة مع Ubuntu 22.04+
          sudo apt-get install -y git zip unzip openjdk-11-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libffi-dev libssl-dev
          # تثبيت build-essential الذي يحتوي على أدوات بناء أساسية
          sudo apt-get install -y build-essential
          pip install --upgrade pip
          pip install cython==0.29.34  # تحديد إصدار Cython لتجنب مشاكل التوافق
          pip install buildozer

      - name: Run Buildozer
        run: |
          buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
